lcgcmt_installarea=with_installarea
CMTPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/dqm-common/dqm-common-00-21-05:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/tdaq-common/tdaq-common-01-20-05:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
CMT_tag=$(tag)
CMTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/CMT/v1r25
CMT_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/CMT/v1r25
CMTVERSION=v1r25
CMT_offset=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=${SLC4_Compat_bin}:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/share/bin:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/scripts:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/${CMTCONFIG}/bin:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/ROOT/5.34.07a/x86_64-slc6-gcc47-opt/root/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/xrootd/3.2.7/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/gccxml/0.9.0_20120309p2/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/tcmalloc/1.7p3/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Python/2.7.3/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/gcc/4.7.2/x86_64-slc6/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/CMT/v1r25/${CMTBIN}:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/qt/4.8.4/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/pygraphics/1.4_python2.7/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/pyanalysis/1.3_python2.7/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/sqlite/3070900/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Java/Ant/1.7.0/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/pytools/1.8_python2.7/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/oracle/11.2.0.3.0/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/COOL/COOL_2_8_18/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/CORAL/CORAL_2_3_27/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSite/gcc-links/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/PandaClient/0.4.40/bin:/afs/cern.ch/atlas/scripts:/usr/sue/bin:/usr/kerberos/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Java/JDK/1.6.0/amd64/jre/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Java/JDK/1.6.0/amd64/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/tdaq-common/tdaq-common-01-20-05/installed/x86_64-slc6-gcc47-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/dqm-common/dqm-common-00-21-05/installed/x86_64-slc6-gcc47-opt/bin
CLASSPATH=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/CMT/v1r25/java
debug_option=-g
cc=$(cc_name)
cdebugflags=$(coptimized_s)
cflags=-fPIC -fmessage-length=0 -fPIC  -g  -std=c11 
pp_cflags= $(CppSpecificFlags) $(CppSpecificFlags)
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clinkflags=-fPIC
clink=$(cc) $(clinkflags) $(cdebugflags)
cdepflags=-MMD -MP -MF $*.d -MQ $@
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -D_GNU_SOURCE -pthread -pipe -ansi -fPIC -W -Wall  -Wno-deprecated -g  -pedantic -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-long-long  -std=c++11 
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT  -DBOOST_FILESYSTEM_VERSION=3  -DATLAS_GAUDI_V21  -DNDEBUG  $(CppSpecificFlags) $(CppSpecificFlags)
cppcomp=$(cpp) -c $(cppdebugflags) $(cppflags) $(pp_cppflags) $(includes)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl -Wl,--as-needed -Wl,--no-undefined  -Wl,--export-dynamic  -Wl,--allow-shlib-undefined  -Wl,--hash-style=both 
cpplink=$(cpp) $(cpplinkflags)
cppdepflags=-MMD -MP -MF $*.d -MQ $@
for=$(for_name)
fflags=-fmessage-length=0 -O2 -fdollar-ok -w -fPIC -g 
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp_name) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=$(ExternalPolicy_root)/scripts/symlink.sh
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo --log=./install.$(tag).history 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.$(tag).history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(symlink_command)
cmt_uninstall_area_command=$(uninstall_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^s/][^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc65-gcc472
MuonMomentumCorrections_tag=$(tag)
MUONMOMENTUMCORRECTIONSROOT=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/MuonSlimming/WmunuPowPyMonteCarlo/MuonMomentumCorrections
MuonMomentumCorrections_root=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/MuonSlimming/WmunuPowPyMonteCarlo/MuonMomentumCorrections
MUONMOMENTUMCORRECTIONSVERSION=MuonMomentumCorrections-00-05-03
MuonMomentumCorrections_cmtpath=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5
MuonMomentumCorrections_offset=MuonSlimming/WmunuPowPyMonteCarlo
MuonMomentumCorrections_project=public
MuonMomentumCorrections_project_release=17.2.10.5
AtlasPolicy_tag=$(tag)
ATLASPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/AtlasPolicy
AtlasPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/AtlasPolicy
ATLASPOLICYVERSION=AtlasPolicy-01-07-28
AtlasPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
AtlasPolicy_project=AtlasCore
AtlasPolicy_project_release=17.8.0
ExternalPolicy_tag=$(tag)
EXTERNALPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/ExternalPolicy
ExternalPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/ExternalPolicy
EXTERNALPOLICYVERSION=ExternalPolicy-00-01-62
ExternalPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
ExternalPolicy_offset=External
ExternalPolicy_project=AtlasCore
ExternalPolicy_project_release=17.8.0
isProject=${CMTPROJECTPATH}notProject
PlatformPolicy_tag=$(tag)
PLATFORMPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/PlatformPolicy
PlatformPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/PlatformPolicy
PLATFORMPOLICYVERSION=PlatformPolicy-00-00-14
PlatformPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
PlatformPolicy_offset=External
PlatformPolicy_project=AtlasCore
PlatformPolicy_project_release=17.8.0
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/GaudiPolicy
GaudiPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/GaudiPolicy
GAUDIPOLICYVERSION=GaudiPolicy-12-04-06
GaudiPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=v23r6p1
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Settings
LCG_Settings_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_65
LCG_releases=${SITEROOT}/sw/lcg/app/releases
LCG_external=${SITEROOT}/sw/lcg/external
unixdirname=lib64
gcc_config_version=4.7.2
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
clang_config_version=2.8
clang_native_version=$(clang_config_version)
clang_home=$(LCG_external)/llvm/$(clang_native_version)/$(LCG_hostos)
icc_config_version=11.1/072
icc_native_version=$(icc_config_version)
cc_name=lcg-gcc-$(gcc_config_version)
cpp_name=lcg-g++-$(gcc_config_version)
cpplinkname=$(cpp_name)
for_name=lcg-gfortran-$(gcc_config_version)
COMPILER_PATH=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/gcc/4.7.2/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.7.2
LD_LIBRARY_PATH=${SLC4_Compat_lib}:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/${CMTCONFIG}/lib:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/gcc/4.7.2/x86_64-slc6/lib64:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/MCGenerators_lcgcmt65/hydjet/1.6/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSite/gcc-links/x86_64-slc6-gcc47-opt/lib64:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSite/gcc-links/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/coin3d/3.1.3p2/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/soqt/1.5.0_qt4.8.4_coin3d3.1.3p2/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/external/yampl/1.0/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/tdaq-common/tdaq-common-01-20-05/installed/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Java/JDK/1.6.0/amd64/jre/lib/amd64:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Java/JDK/1.6.0/amd64/jre/lib/amd64/server:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Java/JDK/1.6.0/amd64/jre/lib/amd64/native_threads:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Java/JDK/1.6.0/amd64/jre/lib/amd64/xawt:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/dqm-common/dqm-common-00-21-05/installed/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/qwt/6.0.1_qt4.8.4/x86_64-slc6-gcc47-opt/lib:/usr/lib64:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Python/2.7.3/x86_64-slc6-gcc47-opt/lib
Python_tag=$(tag)
PYTHONROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/Python
Python_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_65
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Configuration
LCG_Configuration_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_65
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Platforms
LCG_Platforms_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_65
LCG_arch=x86_64
LCG_os=slc6
LCG_compiler=gcc47
LCG_mode=opt
LCG_basesystem=$(LCG_arch)-$(LCG_os)-$(LCG_compiler)
LCG_system=$(LCG_basesystem)-opt
LCG_platform=$(LCG_basesystem)-$(LCG_mode)
ATLAS_TAGS_MAP=none
host_compiler=gcc44
host_arch=x86_64
host_os=slc6
host_cmtconfig=x86_64-slc6-gcc44-opt
LCG_hostos=$(host_arch)-$(host_os)
LCG_hostarch=$(host_arch)
LCG_config_version=65
COOL_config_version=COOL_2_8_18
CORAL_config_version=CORAL_2_3_27
RELAX_config_version=RELAX_1_3_0l
ROOT_config_version=5.34.07a
AIDA_config_version=3.2.1
4suite_config_version=1.0.2p1
bjam_config_version=3.1.13
blas_config_version=20110419
Boost_config_version=1.50.0
Boost_file_version=1_50
CASTOR_config_version=2.1.13-6
cernlib_config_version=2006a
cgsigsoap_config_version=1.3.3-1
CLHEP_config_version=1.9.4.7
cmake_config_version=2.8.9
cmt_config_version=v1r20p20081118
coin3d_config_version=3.1.3p2
coverage_config_version=3.5.2
CppUnit_config_version=1.12.1_p1
cx_oracle_config_version=5.1.1
david_config_version=1_36a
dawn_config_version=3_88a
dcache_client_config_version=2.47.6-1
dcache_srm_config_version=1.9.5-23
dcap_config_version=2.47.6
doxygen_config_version=1.8.2
dpm_config_version=1.8.5-1
epel_config_version=20120618
Expat_config_version=2.0.1
fftw_config_version=3.1.2
Frontier_Client_config_version=2.8.5p1
fastjet_config_version=3.0.3
GCCXML_config_version=0.9.0_20120309p2
genshi_config_version=0.6
gfal_config_version=1.13.0-0
globus_config_version=4.0.7-VDT-1.10.1
graphviz_config_version=2.28.0
gridftp_ifce_config_version=2.1.4-2
GSL_config_version=1.10
HepMC_config_version=2.06.08
HepPDT_config_version=2.06.01
igprof_config_version=5.9.6
ipython_config_version=0.12.1
is_ifce_config_version=1.13.0-0
javasdk_config_version=1.6.0
javajni_config_version=$(javasdk_config_version)
json_config_version=2.5.2
kcachegrind_config_version=0.4.6
lapack_config_version=3.4.0
lcgdmcommon_config_version=1.8.5-1
lcginfosites_config_version=2.6.2-1
lcgutils_config_version=1.13.0-0
lcov_config_version=1.9
lfc_config_version=1.8.5-1
libsvm_config_version=2.86
libtool_config_version=2.4.2
libunwind_config_version=5c2cade
lxml_config_version=2.3
matplotlib_config_version=1.1.0
minuit_config_version=5.27.02
mock_config_version=0.8.0
multiprocessing_config_version=2.6.2.1
myproxy_config_version=4.2-VDT-1.10.1
mysql_config_version=5.5.14
mysql_python_config_version=1.2.3
neurobayes_config_version=3.7.0
neurobayes_expert_config_version=3.7.0
nose_config_version=1.1.2
numpy_config_version=1.6.1
oracle_config_version=11.2.0.3.0
processing_config_version=0.52
py_config_version=1.4.8
py2neo_config_version=1.4.6
pydot_config_version=1.0.28
pyanalysis_config_version=1.3
pygraphics_config_version=1.4
pygsi_config_version=0.5
pylint_config_version=0.26.0
pyminuit_config_version=0.0.1
pytest_config_version=2.2.4
pytools_config_version=1.8
Python_config_version=2.7.3
Python_config_version_twodigit=2.7
pyqt_config_version=4.9.5
pyparsing_config_version=1.5.6
pyxml_config_version=0.8.4p1
QMtest_config_version=2.4.1
qt_config_version=4.8.4
qwt_config_version=6.0.1
readline_config_version=2.5.1p1
roofit_config_version=3.10p1
setuptools_config_version=0.6c11
scipy_config_version=0.10.0
sip_config_version=4.14
soqt_config_version=1.5.0
sqlalchemy_config_version=0.7.7
sqlite_config_version=3070900
srm_ifce_config_version=1.13.0-0
stomppy_config_version=3.1.3
storm_config_version=0.19
sympy_config_version=0.7.1
tbb_config_version=41_20121003
tcmalloc_config_version=1.7p3
uuid_config_version=1.42
valgrind_config_version=3.8.0
vdt_config_version=0.3.2
voms_config_version=2.0.8-1
vomsapic_config_version=1.9.17-1
vomsapicpp_config_version=1.9.17-1
vomsapi_noglobus_config_version=1.9.17-1
vomsclients_config_version=1.9.17-1
XercesC_config_version=3.1.1p1
xqilla_config_version=2.2.4p1
xrootd_config_version=3.2.7
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
DYLD_LIBRARY_PATH=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/qt/4.8.4/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/coin3d/3.1.3p2/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/soqt/1.5.0_qt4.8.4_coin3d3.1.3p2/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/qwt/6.0.1_qt4.8.4/x86_64-slc6-gcc47-opt/lib
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/ROOT/5.34.07a/x86_64-slc6-gcc47-opt/root/man:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/tcmalloc/1.7p3/x86_64-slc6-gcc47-opt/share/man:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/libunwind/5c2cade/x86_64-slc6-gcc47-opt/man:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/Python/2.7.3/x86_64-slc6-gcc47-opt/share/man:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/gccxml/0.9.0_20120309p2/x86_64-slc6-gcc47-opt/share/man:/usr/kerberos/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man/en:/usr/share/man:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/ROOT/5.34.07a/src/root/man
tcmalloc_tag=$(tag)
TCMALLOCROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/tcmalloc
tcmalloc_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_65
libunwind_tag=$(tag)
LIBUNWINDROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/libunwind
libunwind_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_65
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86_64
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
copyInclude=cp -Rup 
python_bin_module_dir=$(tag)/python
cmt_actions_constituents=      doxygen post_install post_merge_rootmap post_merge_genconfdb post_build_tpcnvdb all_post_constituents checkreq SLC5_Compat_install_action Mac105_Compat_install_action  check_install_runtime check_install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap 
cmt_actions_constituentsclean= check_install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmapclean check_install_runtimeclean new_rootsysclean Mac105_Compat_install_actionclean SLC5_Compat_install_actionclean checkreqclean all_post_constituentsclean post_build_tpcnvdbclean post_merge_genconfdbclean post_merge_rootmapclean post_installclean doxygenclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
lib_no_static_fragment=library_no_static
cppdebugflags_s=-g
cppoptimized_s=-O2 -DNDEBUG
cppprofiled_s=-pg
cdebugflags_s=-g
coptimized_s=-O2 -DNDEBUG
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2 -DNDEBUG
fprofiled_s=-pg
gccxml_cppflags= -D__STRICT_ANSI__
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000  -Wl,--hash-style=both 
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000  -Wl,--hash-style=both 
application_linkopts=-Wl,--export-dynamic 
genconfDir=$(shared_install_subdir)/genConf/
merge_genconfDb_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiCoreSvc=GaudiCoreSvc * -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
COOLVERS=COOL_2_8_18
CORALVERS=CORAL_2_3_27
ROOTVERS=5.34.07a
BoostVERS=1.50.0
uuidVERS=1.42
GCCXMLVERS=0.9.0_20120309p2
AIDAVERS=3.2.1
XercesCVERS=3.1.1p1
GSLVERS=1.10
PythonVERS=2.7.3
HepMCVERS=2.06.08
QMtestVERS=2.4.1
LCGCMTVERS=65
GAUDI_DOXY_HOME=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/GaudiRelease/doc
AtlasCommonPolicy_tag=$(tag)
ATLASCOMMONPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/AtlasCommonPolicy
AtlasCommonPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/AtlasCommonPolicy
ATLASCOMMONPOLICYVERSION=AtlasCommonPolicy-00-00-24
AtlasCommonPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0
AtlasCommonPolicy_project=DetCommon
AtlasCommonPolicy_project_release=17.8.0
AtlasDoxygen_tag=$(tag)
ATLASDOXYGENROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/Tools/AtlasDoxygen
AtlasDoxygen_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/Tools/AtlasDoxygen
ATLASDOXYGENVERSION=AtlasDoxygen-00-03-03
AtlasDoxygen_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0
AtlasDoxygen_offset=Tools
AtlasDoxygen_project=DetCommon
AtlasDoxygen_project_release=17.8.0
library_fragment=library
SEPARATEDEBUG=1
debuginfosuffix=.debug
all_dependencies= checkreq 
as_needed_macro=asNeeded
SLC5_Compat_tag=$(tag)
SLC5_COMPATROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/SLC5_Compat
SLC5_Compat_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/SLC5_Compat
SLC5_COMPATVERSION=SLC5_Compat-00-00-02
SLC5_Compat_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
SLC5_Compat_offset=External
SLC5_Compat_project=AtlasCore
SLC5_Compat_project_release=17.8.0
AtlasExternalArea_tag=$(tag)
ATLASEXTERNALAREAROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasExternalArea
AtlasExternalArea_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasExternalArea
ATLASEXTERNALAREAVERSION=AtlasExternalArea-00-00-25
AtlasExternalArea_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
AtlasExternalArea_offset=External
AtlasExternalArea_project=AtlasCore
AtlasExternalArea_project_release=17.8.0
ATLAS_EXTERNAL=${SITEROOT}/external
LCG_ROOT=${SITEROOT}/sw/lcg
LCG_EXTERNAL=${LCG_ROOT}/external
LCG_app_system=$(LCG_platform)
LCG_ext_system=$(LCG_system)
COMMON_PACKAGES=${SITEROOT}/packages
SLC5_Compat_native_version=1.0.2
SLC5_Compat_platform=NotSupported
SLC5_Compat_base=$(ATLAS_EXTERNAL)/slc5compat/$(SLC5_Compat_native_version)
SLC5_Compat_home=$(SLC5_Compat_base)/$(SLC5_Compat_platform)
SLC5_Compat_home_install=$(SLC5_Compat_root)/$(CMTCONFIG)/slc5compat
SLC5_Compat_install_cmd=$(library_install_command) $(SLC5_Compat_home) $(SLC5_Compat_home_install)
Mac105_Compat_tag=$(tag)
MAC105_COMPATROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/Mac105_Compat
Mac105_Compat_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/Mac105_Compat
MAC105_COMPATVERSION=Mac105_Compat-00-00-01
Mac105_Compat_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
Mac105_Compat_offset=External
Mac105_Compat_project=AtlasCore
Mac105_Compat_project_release=17.8.0
Mac105_Compat_native_version=1.0.0
Mac105_Compat_platform=NotSupported
Mac105_Compat_base=$(ATLAS_EXTERNAL)/mac105compat/$(Mac105_Compat_native_version)
Mac105_Compat_home=$(Mac105_Compat_base)/$(Mac105_Compat_platform)
Mac105_Compat_home_install=$(Mac105_Compat_root)/$(CMTCONFIG)
Mac105_Compat_install_cmd=$(library_install_command) $(Mac105_Compat_home) $(Mac105_Compat_home_install)
ExternalPolicy_scripts= -s=$(EXTERNALPOLICYROOT)/share -s=$(EXTERNALPOLICYROOT)/src symlink.sh inverse_symlink.sh 
symlink_command=$(ExternalPolicy_root)/src/symlink.sh
symlinknew=$(symlink_command)
copy_command=cp -R -H
atlas_install_command=cp -R -H
base_URL=http://atlas.web.cern.ch/Atlas/GROUPS/SOFTWARE/OO/dist/
kits_dir=cmt/kits
zip_command=tar
AtlasCxxPolicy_tag=$(tag)
ATLASCXXPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/AtlasCxxPolicy
AtlasCxxPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/AtlasCxxPolicy
ATLASCXXPOLICYVERSION=AtlasCxxPolicy-00-00-62
AtlasCxxPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
AtlasCxxPolicy_project=AtlasCore
AtlasCxxPolicy_project_release=17.8.0
AtlasCompilers_tag=$(tag)
ATLASCOMPILERSROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/External/AtlasCompilers
AtlasCompilers_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/External/AtlasCompilers
ATLASCOMPILERSVERSION=AtlasCompilers-00-00-18
AtlasCompilers_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0
AtlasCompilers_offset=External
AtlasCompilers_project=DetCommon
AtlasCompilers_project_release=17.8.0
compiler_versions=gcc=$(gcc_config_version):icc=$(icc_config_version):llvm=$(clang_config_version)
AtlasCxxPolicy_pp_cppflags= -DHAVE_PRETTY_FUNCTION -DHAVE_LONG_LONG -DHAVE_BOOL -DHAVE_EXPLICIT -DHAVE_MUTABLE -DHAVE_SIGNED -DHAVE_TYPENAME -DHAVE_NEW_STYLE_CASTS -DHAVE_DYNAMIC_CAST -DHAVE_TYPEID -DHAVE_ANSI_TEMPLATE_INSTANTIATION -DHAVE_TEMPLATE_DEFAULT_ARGS -DHAVE_BROKEN_TEMPLATE_RESCOPE -DHAVE_TEMPLATE_NULL_ARGS -DHAVE_TEMPLATE_NULL_SPEC -DHAVE_TEMPLATE_PARTIAL_SPEC -DHAVE_MEMBER_TEMPLATES -DHAVE_ANSI_OPERATOR_ARROW -DHAVE_NAMESPACES -DHAVE_NAMESPACE_STD -DHAVE_NEW_IOSTREAMS -DHAVE_OSTREAM_CHAR_OVERLOAD -DHAVE_ITERATOR_TRAITS -DHAVE_ITERATOR -DHAVE_REVERSE_ITERATOR_STYLE -DHAVE_CXX_STDC_HEADERS -DHAVE_64_BITS -D__IDENTIFIER_64BIT__  '-DPACKAGE_VERSION=$(q2)$(version)$(q2)' -DPACKAGE_VERSION_UQ=$(version)  -DNDEBUG $(pp_cppflags)
q2="
NICOS=NICOS${NICOS_PROJECT_RELNAME}
NICOS_TMP_A=NICOS$(NICOS_PROJECT_HOME)
NICOS_TMP_B=NICOS$(NICOS_COPY_HOME)
NICOS_TMP_C=NICOS$(NICOS_PROJECT_RELNAME_COPY)
CodeCheck_tag=$(tag)
CODECHECKROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/Tools/CodeCheck
CodeCheck_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/Tools/CodeCheck
CODECHECKVERSION=CodeCheck-01-02-03
CodeCheck_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
CodeCheck_offset=Tools
CodeCheck_project=AtlasCore
CodeCheck_project_release=17.8.0
asNeeded_linkopt=-Wl,--as-needed
notAsNeeded_linkopt=-Wl,--no-as-needed
abuild_gen_tpcnv_cmd=$(AtlasPolicy_root)/scripts/abuild-gen-tpcnvdb.py
MAKEFLAGS= --no-print-directory 
genCLIDDB_cmd=${AtlasPolicy_root}/cmt/fragments/gencliddb.py
use_CLIDComps=CLIDComps * Control -no_auto_imports
remote_launcher=ssh -f 
dependencies_fragment=dependencies
install_include_filter=*.h
AtlasPolicy_scripts= -s=../share checkreq.py 
AtlasROOT_tag=$(tag)
ATLASROOTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasROOT
AtlasROOT_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasROOT
ATLASROOTVERSION=AtlasROOT-02-03-08
AtlasROOT_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
AtlasROOT_offset=External
AtlasROOT_project=AtlasCore
AtlasROOT_project_release=17.8.0
ROOT_tag=$(tag)
ROOTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/ROOT
ROOT_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_65
GCCXML_tag=$(tag)
GCCXMLROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/GCCXML
GCCXML_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_65
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
xrootd_tag=$(tag)
XROOTDROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/xrootd
xrootd_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/xrootd
XROOTDVERSION=v1
xrootd_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
xrootd_offset=LCG_Interfaces
xrootd_project=LCGCMT
xrootd_project_release=LCGCMT_65
xrootd_native_version=$(xrootd_config_version)
xrootd_home=$(LCG_external)/xrootd/$(xrootd_native_version)/$(LCG_system)
xrootd_linkopts=-L$(xrootd_home)/$(unixdirname) 
xrootd_export_paths= $(xrootd_home)/bin $(xrootd_home)/include $(xrootd_home)/$(unixdirname)   $(xrootd_home)/share
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts= $(rootRooFitLibs) $(rootMathLibs) $(rootBasicLibs) $(rootRFIOLibs) $(rootGraphicsLibs) $(rootTableLibs) $(rootSTLDictLibs)  -lRIO
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/ROOT/5.34.07a/x86_64-slc6-gcc47-opt/root
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/python:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/${CMTCONFIG}/lib/python2.7:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/ROOT/5.34.07a/x86_64-slc6-gcc47-opt/root/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/pygraphics/1.4_python2.7/x86_64-slc6-gcc47-opt/lib/python2.7/site-packages:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/pyanalysis/1.3_python2.7/x86_64-slc6-gcc47-opt/lib/python2.7/site-packages:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/external/ZSI/2.1-a1/lib/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/pytools/1.8_python2.7/x86_64-slc6-gcc47-opt/lib/python2.7/site-packages:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/COOL/COOL_2_8_18/x86_64-slc6-gcc47-opt/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/CORAL/CORAL_2_3_27/x86_64-slc6-gcc47-opt/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/CORAL/CORAL_2_3_27/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/PandaClient/0.4.40/lib/python2.4/site-packages:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/tdaq-common/tdaq-common-01-20-05/installed/share/lib/python:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/tdaq-common/tdaq-common-01-20-05/installed/x86_64-slc6-gcc47-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/dqm-common/dqm-common-00-21-05/installed/share/lib/python
rootcint=rootcint
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
rootBasicLibs=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread -lMathCore -lHist
rootMathLibs=-L$(ROOT_home)/lib  -lMathMore -lMinuit -lMinuit2 -lMatrix -lPhysics -lHistPainter -lHist -lRint
rootGraphicsLibs=-L$(ROOT_home)/lib -lGraf -lGraf3d -lGpad -lHtml -lPostscript -lGui -lGX11TTF -lGX11
MuonMomentumCorrections_installed_dependencies= MuonMomentumCorrections
MuonMomentumCorrections_library_dependencies= MuonMomentumCorrections
MuonMomentumCorrections_installed_shlibflags= -lMuonMomentumCorrections 
MuonMomentumCorrections_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(MuonMomentumCorrections_use_linkopts) $(MuonMomentumCorrections_extra_shlibflags)
MuonMomentumCorrections_use_linkopts=    $(AtlasPolicy_linkopts)  $(AtlasCxxPolicy_linkopts)  $(AtlasROOT_linkopts)  $(ExternalPolicy_linkopts)  $(SLC5_Compat_linkopts)  $(Mac105_Compat_linkopts)  $(AtlasExternalArea_linkopts)  $(PlatformPolicy_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(AtlasCommonPolicy_linkopts)  $(AtlasDoxygen_linkopts)  $(xrootd_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(AtlasCompilers_linkopts)  $(LCG_Platforms_linkopts)  $(CodeCheck_linkopts) 
MuonMomentumCorrections_linkopts= -lMuonMomentumCorrections  
apply_optdebug_library=with_optdebug_library
MuonMomentumCorrections_optdebug_library_dependencies= MuonMomentumCorrections
MuonMomentumCorrections_runtime= -s=../share *.dat  
install_runtime_dependencies=check_install_runtime
AtlasReflex_tag=$(tag)
ATLASREFLEXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasReflex
AtlasReflex_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasReflex
ATLASREFLEXVERSION=AtlasReflex-00-02-35
AtlasReflex_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
AtlasReflex_offset=External
AtlasReflex_project=AtlasCore
AtlasReflex_project_release=17.8.0
Reflex_tag=$(tag)
REFLEXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/Reflex
Reflex_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_65
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
AtlasRELAX_tag=$(tag)
ATLASRELAXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasRELAX
AtlasRELAX_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/External/AtlasRELAX
ATLASRELAXVERSION=AtlasRELAX-00-01-00
AtlasRELAX_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
AtlasRELAX_offset=External
AtlasRELAX_project=AtlasCore
AtlasRELAX_project_release=17.8.0
RELAX_tag=$(tag)
RELAXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/RELAX
RELAX_root=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/LCG_Interfaces/RELAX
RELAXVERSION=v1
RELAX_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
RELAX_offset=LCG_Interfaces
RELAX_project=LCGCMT
RELAX_project_release=LCGCMT_65
RELAX_native_version=$(RELAX_config_version)
RELAX_base=$(LCG_releases)/RELAX/$(RELAX_native_version)
RELAX_home=$(RELAX_base)/$(LCG_platform)
RELAX_export_paths= $(RELAX_home)/lib  
athena_genreflex_wrapper_cmd=python $(AtlasReflex_root)/cmt/athena_genreflex_wrapper.py
merge_dict_rootmap_cmd=${GaudiPolicy_root}/scripts/merge_files.py
dict_dir=$(bin)dict
MuonMomentumCorrectionsGen_dependencies= install_includes
lib_MuonMomentumCorrectionsDict_cppflags= -std=c++03 
MuonMomentumCorrectionsDict_pp_cppflags= -I. -ftemplate-depth-125  -g 
MuonMomentumCorrectionsDict_dependencies= MuonMomentumCorrectionsGen  $(MuonMomentumCorrections_library_dependencies)
reflex_dictMuonMomentumCorrections_clean_target= MuonMomentumCorrectionsDictclean 
reflex_dictMuonMomentumCorrections_selection_file= ../MuonMomentumCorrections/selection.xml 
reflex_dictMuonMomentumCorrections_navigables=  
reflex_dictMuonMomentumCorrections_data_links=  
reflex_dictMuonMomentumCorrections_element_links=  
reflex_dictMuonMomentumCorrections_element_link_vectors=  
reflex_dictMuonMomentumCorrections_opt_rootmap= --rootmap=MuonMomentumCorrectionsDict.dsomap --rootmap-lib=$(libprefix)MuonMomentumCorrectionsDict.$(shlibsuffix) 
reflex_dictMuonMomentumCorrections_options=   --select=$(dict_dir)/MuonMomentumCorrections_selection.xml  -DNDEBUG $(reflex_dictMuonMomentumCorrections_opt_rootmap)  --gccxmlpath=$(GCCXML_home)/bin  --fail_on_warnings  --fail_on_warnings $(reflex_dict_options_cppflags) 
MuonMomentumCorrectionsDict_shlibflags=$(componentshr_linkopts) $(use_linkopts) $(Reflex_linkopts) $(MuonMomentumCorrections_extra_shlibflags)
MuonMomentumCorrections_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap= $(dict_dir)/MuonMomentumCorrections/MuonMomentumCorrectionsDict.dsomap 
install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap_dependencies=check_install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap MuonMomentumCorrectionsGen 
MuonMomentumCorrectionsDict_optdebug_library_dependencies= MuonMomentumCorrectionsDict
check_install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap_dependencies= MuonMomentumCorrectionsGen 
run_merge_dict_cmd=do_real_merge_dict_dsomap
MuonMomentumCorrectionsDictMerge_dependencies= MuonMomentumCorrectionsDict 
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
PlatformPolicyDir=${PLATFORMPOLICYROOT}/${BINDIR}
AtlasExternalAreaDir=${ATLASEXTERNALAREAROOT}/${BINDIR}
SLC5_CompatDir=${SLC5_COMPATROOT}/${BINDIR}
Mac105_CompatDir=${MAC105_COMPATROOT}/${BINDIR}
ExternalPolicyDir=${EXTERNALPOLICYROOT}/${BINDIR}
AtlasCxxPolicyDir=${ATLASCXXPOLICYROOT}/${BINDIR}
AtlasPolicyDir=${ATLASPOLICYROOT}/${BINDIR}
AtlasROOTDir=${ATLASROOTROOT}/${BINDIR}
AtlasRELAXDir=${ATLASRELAXROOT}/${BINDIR}
AtlasReflexDir=${ATLASREFLEXROOT}/${BINDIR}
MuonMomentumCorrectionsDir=${MUONMOMENTUMCORRECTIONSROOT}/${BINDIR}
MuonMomentumCorrections_include_dirs=$(MUONMOMENTUMCORRECTIONSROOT)
CMTUSERCONTEXT_tag=$(tag)
CMTUSERCONTEXTROOT=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/MuonSlimming/WmunuPowPyMonteCarlo/MuonMomentumCorrections/cmt/CMTUSERCONTEXT
CMTUSERCONTEXT_root=/CMTUSERCONTEXT
CMTUSERCONTEXTVERSION=v0
CMTUSERCONTEXT_cmtpath=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt
CMTUSERCONTEXT_project=CMTUSERCONTEXT
CMTUSERCONTEXT_project_release=cmt
tag=x86_64-slc6-gcc47-opt
package=MuonMomentumCorrections
version=MuonMomentumCorrections-00-05-03
PACKAGE_ROOT=$(MUONMOMENTUMCORRECTIONSROOT)
srcdir=../src
bin=../$(MuonMomentumCorrections_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/MuonSlimming/WmunuPowPyMonteCarlo/MuonMomentumCorrections/x86_64-slc6-gcc47-opt/
project=public
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(LCGCMT_installarea_prefix)/$(CMTCONFIG)/lib $(LCGCMT_installarea_prefix)/share/lib $(LCGCMT_installarea_prefix)/share/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(DetCommon_installarea_prefix)/$(CMTCONFIG)/lib $(DetCommon_installarea_prefix)/share/lib $(DetCommon_installarea_prefix)/share/bin $(AtlasCore_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasCore_installarea_prefix)/share/lib $(AtlasCore_installarea_prefix)/share/bin $(AtlasConditions_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasConditions_installarea_prefix)/share/lib $(AtlasConditions_installarea_prefix)/share/bin $(AtlasEvent_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasEvent_installarea_prefix)/share/lib $(AtlasEvent_installarea_prefix)/share/bin $(AtlasReconstruction_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasReconstruction_installarea_prefix)/share/lib $(AtlasReconstruction_installarea_prefix)/share/bin $(AtlasTrigger_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasTrigger_installarea_prefix)/share/lib $(AtlasTrigger_installarea_prefix)/share/bin $(AtlasSimulation_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasSimulation_installarea_prefix)/share/lib $(AtlasSimulation_installarea_prefix)/share/bin $(AtlasAnalysis_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasAnalysis_installarea_prefix)/share/lib $(AtlasAnalysis_installarea_prefix)/share/bin $(AtlasOffline_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasOffline_installarea_prefix)/share/lib $(AtlasOffline_installarea_prefix)/share/bin $(AtlasProduction_installarea_prefix)/$(CMTCONFIG)/lib $(AtlasProduction_installarea_prefix)/share/lib $(AtlasProduction_installarea_prefix)/share/bin $(public_installarea_prefix)/$(CMTCONFIG)/lib $(public_installarea_prefix)/share/lib $(public_installarea_prefix)/share/bin $(CMTUSERCONTEXT_installarea_prefix)/$(CMTCONFIG)/lib $(CMTUSERCONTEXT_installarea_prefix)/share/lib $(CMTUSERCONTEXT_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(MuonMomentumCorrections_linkopts)  $(AtlasPolicy_linkopts)  $(AtlasCxxPolicy_linkopts)  $(AtlasROOT_linkopts)  $(ExternalPolicy_linkopts)  $(SLC5_Compat_linkopts)  $(Mac105_Compat_linkopts)  $(AtlasExternalArea_linkopts)  $(PlatformPolicy_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(AtlasCommonPolicy_linkopts)  $(AtlasDoxygen_linkopts)  $(xrootd_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(AtlasCompilers_linkopts)  $(LCG_Platforms_linkopts)  $(CodeCheck_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
DetCommon_installarea_prefix=$(cmt_installarea_prefix)
DetCommon_installarea_prefix_remove=$(DetCommon_installarea_prefix)
tdaq-common_installarea_prefix=$(cmt_installarea_prefix)
tdaq-common_installarea_prefix_remove=$(tdaq-common_installarea_prefix)
AtlasCore_installarea_prefix=$(cmt_installarea_prefix)
AtlasCore_installarea_prefix_remove=$(AtlasCore_installarea_prefix)
AtlasConditions_installarea_prefix=$(cmt_installarea_prefix)
AtlasConditions_installarea_prefix_remove=$(AtlasConditions_installarea_prefix)
dqm-common_installarea_prefix=$(cmt_installarea_prefix)
dqm-common_installarea_prefix_remove=$(dqm-common_installarea_prefix)
AtlasEvent_installarea_prefix=$(cmt_installarea_prefix)
AtlasEvent_installarea_prefix_remove=$(AtlasEvent_installarea_prefix)
AtlasReconstruction_installarea_prefix=$(cmt_installarea_prefix)
AtlasReconstruction_installarea_prefix_remove=$(AtlasReconstruction_installarea_prefix)
AtlasTrigger_installarea_prefix=$(cmt_installarea_prefix)
AtlasTrigger_installarea_prefix_remove=$(AtlasTrigger_installarea_prefix)
AtlasSimulation_installarea_prefix=$(cmt_installarea_prefix)
AtlasSimulation_installarea_prefix_remove=$(AtlasSimulation_installarea_prefix)
AtlasAnalysis_installarea_prefix=$(cmt_installarea_prefix)
AtlasAnalysis_installarea_prefix_remove=$(AtlasAnalysis_installarea_prefix)
AtlasOffline_installarea_prefix=$(cmt_installarea_prefix)
AtlasOffline_installarea_prefix_remove=$(AtlasOffline_installarea_prefix)
AtlasProduction_installarea_prefix=$(cmt_installarea_prefix)
AtlasProduction_installarea_prefix_remove=$(AtlasProduction_installarea_prefix)
public_installarea_prefix=$(cmt_installarea_prefix)
public_installarea_prefix_remove=$(public_installarea_prefix)
CMTUSERCONTEXT_installarea_prefix=$(cmt_installarea_prefix)
CMTUSERCONTEXT_installarea_prefix_remove=$(CMTUSERCONTEXT_installarea_prefix)
cmt_installarea_linkopts= -L/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/$(public_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/$(AtlasProduction_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/$(AtlasOffline_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/$(AtlasAnalysis_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/$(AtlasSimulation_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/$(AtlasTrigger_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/$(AtlasReconstruction_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/$(AtlasEvent_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/$(AtlasConditions_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/$(AtlasCore_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/$(DetCommon_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/$(LCGCMT_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65
GAUDI_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1
DetCommon_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0
tdaq-common_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/tdaq-common/tdaq-common-01-20-05
AtlasCore_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0
AtlasConditions_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0
dqm-common_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/dqm-common/dqm-common-00-21-05
AtlasEvent_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0
AtlasReconstruction_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0
AtlasTrigger_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0
AtlasSimulation_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0
AtlasAnalysis_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0
AtlasOffline_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0
AtlasProduction_home=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2
public_home=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5
CMTUSERCONTEXT_home=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt
lcgcmt_pp=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(LCGCMT_installarea_prefix)/$(CMTCONFIG)/lib/python$(Python_config_version_twodigit)/site-packages
CMTUSERCONTEXT_install_include= /cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)$(shared_install_subdir)/include 
public_install_include= /afs/cern.ch/user/t/tbalestr/public/17.2.10.5/$(public_installarea_prefix)$(shared_install_subdir)/include 
AtlasProduction_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/$(AtlasProduction_installarea_prefix)$(shared_install_subdir)/include 
AtlasOffline_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/$(AtlasOffline_installarea_prefix)$(shared_install_subdir)/include 
AtlasAnalysis_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/$(AtlasAnalysis_installarea_prefix)$(shared_install_subdir)/include 
AtlasSimulation_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/$(AtlasSimulation_installarea_prefix)$(shared_install_subdir)/include 
AtlasTrigger_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/$(AtlasTrigger_installarea_prefix)$(shared_install_subdir)/include 
AtlasReconstruction_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/$(AtlasReconstruction_installarea_prefix)$(shared_install_subdir)/include 
AtlasEvent_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/$(AtlasEvent_installarea_prefix)$(shared_install_subdir)/include 
AtlasConditions_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/$(AtlasConditions_installarea_prefix)$(shared_install_subdir)/include 
AtlasCore_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/$(AtlasCore_installarea_prefix)$(shared_install_subdir)/include 
DetCommon_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/$(DetCommon_installarea_prefix)$(shared_install_subdir)/include 
GAUDI_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/$(GAUDI_installarea_prefix)$(shared_install_subdir)/include 
LCGCMT_install_include= /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/$(LCGCMT_installarea_prefix)$(shared_install_subdir)/include 
LCGCMT_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/$(LCGCMT_installarea_prefix)$(shared_install_subdir)/python
GAUDI_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/$(GAUDI_installarea_prefix)$(shared_install_subdir)/python
DetCommon_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/$(DetCommon_installarea_prefix)$(shared_install_subdir)/python
AtlasCore_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/$(AtlasCore_installarea_prefix)$(shared_install_subdir)/python
AtlasConditions_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/$(AtlasConditions_installarea_prefix)$(shared_install_subdir)/python
AtlasEvent_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/$(AtlasEvent_installarea_prefix)$(shared_install_subdir)/python
AtlasReconstruction_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/$(AtlasReconstruction_installarea_prefix)$(shared_install_subdir)/python
AtlasTrigger_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/$(AtlasTrigger_installarea_prefix)$(shared_install_subdir)/python
AtlasSimulation_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/$(AtlasSimulation_installarea_prefix)$(shared_install_subdir)/python
AtlasAnalysis_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/$(AtlasAnalysis_installarea_prefix)$(shared_install_subdir)/python
AtlasOffline_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/$(AtlasOffline_installarea_prefix)$(shared_install_subdir)/python
AtlasProduction_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/$(AtlasProduction_installarea_prefix)$(shared_install_subdir)/python
public_install_python=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/$(public_installarea_prefix)$(shared_install_subdir)/python
CMTUSERCONTEXT_install_python=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)$(shared_install_subdir)/python
LCGCMT_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/$(LCGCMT_installarea_prefix)/$(python_bin_module_dir)
GAUDI_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/$(GAUDI_installarea_prefix)/$(python_bin_module_dir)
DetCommon_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/$(DetCommon_installarea_prefix)/$(python_bin_module_dir)
AtlasCore_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/$(AtlasCore_installarea_prefix)/$(python_bin_module_dir)
AtlasConditions_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/$(AtlasConditions_installarea_prefix)/$(python_bin_module_dir)
AtlasEvent_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/$(AtlasEvent_installarea_prefix)/$(python_bin_module_dir)
AtlasReconstruction_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/$(AtlasReconstruction_installarea_prefix)/$(python_bin_module_dir)
AtlasTrigger_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/$(AtlasTrigger_installarea_prefix)/$(python_bin_module_dir)
AtlasSimulation_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/$(AtlasSimulation_installarea_prefix)/$(python_bin_module_dir)
AtlasAnalysis_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/$(AtlasAnalysis_installarea_prefix)/$(python_bin_module_dir)
AtlasOffline_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/$(AtlasOffline_installarea_prefix)/$(python_bin_module_dir)
AtlasProduction_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/$(AtlasProduction_installarea_prefix)/$(python_bin_module_dir)
public_install_pyd_module=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/$(public_installarea_prefix)/$(python_bin_module_dir)
CMTUSERCONTEXT_install_pyd_module=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)/$(python_bin_module_dir)
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
LCGCMT_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/$(LCGCMT_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
GAUDI_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/$(GAUDI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
DetCommon_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/$(DetCommon_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasCore_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/$(AtlasCore_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasConditions_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/$(AtlasConditions_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasEvent_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/$(AtlasEvent_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasReconstruction_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/$(AtlasReconstruction_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasTrigger_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/$(AtlasTrigger_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasSimulation_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/$(AtlasSimulation_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasAnalysis_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/$(AtlasAnalysis_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasOffline_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/$(AtlasOffline_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AtlasProduction_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/$(AtlasProduction_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
public_install_scripts=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/$(public_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
CMTUSERCONTEXT_install_scripts=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
genconfInstallDir=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/$(public_installarea_prefix)$(shared_install_subdir)/python
JOBOPTSEARCHPATH=.:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/jobOptions:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/jobOptions
DATAPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/share:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/database/DBRelease/current:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/PartPropSvc/share:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/atlas/offline/ReleaseData/v16:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/atlas/offline/ReleaseData/v16/testfile:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/atlas/project/magfield/CTB
ROOTMAPSEARCHPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/rootmap:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/rootmap
XMLPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/XML:/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/XML
CMTINSTALLAREA=/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(AtlasPolicy_root)/cmt/requirements $(AtlasCxxPolicy_root)/cmt/requirements $(AtlasROOT_root)/cmt/requirements $(AtlasReflex_root)/cmt/requirements $(AtlasRELAX_root)/cmt/requirements $(ExternalPolicy_root)/cmt/requirements $(SLC5_Compat_root)/cmt/requirements $(Mac105_Compat_root)/cmt/requirements $(AtlasExternalArea_root)/cmt/requirements $(PlatformPolicy_root)/cmt/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(AtlasCommonPolicy_root)/cmt/requirements $(AtlasDoxygen_root)/cmt/requirements $(GCCXML_root)/cmt/requirements $(xrootd_root)/cmt/requirements $(RELAX_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(AtlasCompilers_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements $(CodeCheck_root)/cmt/requirements 
use_includes= $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/AtlasCxxPolicy" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/ROOT/5.34.07a/x86_64-slc6-gcc47-opt/root/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/app/releases/ROOT/5.34.07a/x86_64-slc6-gcc47-opt/root/include" $(ppcmd)"$(AtlasCommonPolicy_root)/src" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/sw/lcg/external/xrootd/3.2.7/x86_64-slc6-gcc47-opt/include" $(ppcmd)"$(AtlasCompilers_root)/src" $(ppcmd)"$(LCG_Platforms_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(MuonMomentumCorrections_stamps)  $(AtlasPolicy_stamps)  $(AtlasCxxPolicy_stamps)  $(AtlasROOT_stamps)  $(ExternalPolicy_stamps)  $(SLC5_Compat_stamps)  $(Mac105_Compat_stamps)  $(AtlasExternalArea_stamps)  $(PlatformPolicy_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(ROOT_stamps)  $(AtlasCommonPolicy_stamps)  $(AtlasDoxygen_stamps)  $(xrootd_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps)  $(AtlasCompilers_stamps)  $(LCG_Platforms_stamps)  $(CodeCheck_stamps) 
use_cflags=  $(MuonMomentumCorrections_cflags)  $(AtlasPolicy_cflags)  $(AtlasCxxPolicy_cflags)  $(AtlasROOT_cflags)  $(ExternalPolicy_cflags)  $(SLC5_Compat_cflags)  $(Mac105_Compat_cflags)  $(AtlasExternalArea_cflags)  $(PlatformPolicy_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(ROOT_cflags)  $(AtlasCommonPolicy_cflags)  $(AtlasDoxygen_cflags)  $(xrootd_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags)  $(AtlasCompilers_cflags)  $(LCG_Platforms_cflags)  $(CodeCheck_cflags) 
use_pp_cflags=  $(MuonMomentumCorrections_pp_cflags)  $(AtlasPolicy_pp_cflags)  $(AtlasCxxPolicy_pp_cflags)  $(AtlasROOT_pp_cflags)  $(ExternalPolicy_pp_cflags)  $(SLC5_Compat_pp_cflags)  $(Mac105_Compat_pp_cflags)  $(AtlasExternalArea_pp_cflags)  $(PlatformPolicy_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(ROOT_pp_cflags)  $(AtlasCommonPolicy_pp_cflags)  $(AtlasDoxygen_pp_cflags)  $(xrootd_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(AtlasCompilers_pp_cflags)  $(LCG_Platforms_pp_cflags)  $(CodeCheck_pp_cflags) 
use_cppflags=  $(MuonMomentumCorrections_cppflags)  $(AtlasPolicy_cppflags)  $(AtlasCxxPolicy_cppflags)  $(AtlasROOT_cppflags)  $(ExternalPolicy_cppflags)  $(SLC5_Compat_cppflags)  $(Mac105_Compat_cppflags)  $(AtlasExternalArea_cppflags)  $(PlatformPolicy_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(ROOT_cppflags)  $(AtlasCommonPolicy_cppflags)  $(AtlasDoxygen_cppflags)  $(xrootd_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags)  $(AtlasCompilers_cppflags)  $(LCG_Platforms_cppflags)  $(CodeCheck_cppflags) 
use_pp_cppflags=  $(MuonMomentumCorrections_pp_cppflags)  $(AtlasPolicy_pp_cppflags)  $(AtlasCxxPolicy_pp_cppflags)  $(AtlasROOT_pp_cppflags)  $(ExternalPolicy_pp_cppflags)  $(SLC5_Compat_pp_cppflags)  $(Mac105_Compat_pp_cppflags)  $(AtlasExternalArea_pp_cppflags)  $(PlatformPolicy_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(ROOT_pp_cppflags)  $(AtlasCommonPolicy_pp_cppflags)  $(AtlasDoxygen_pp_cppflags)  $(xrootd_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(AtlasCompilers_pp_cppflags)  $(LCG_Platforms_pp_cppflags)  $(CodeCheck_pp_cppflags) 
use_fflags=  $(MuonMomentumCorrections_fflags)  $(AtlasPolicy_fflags)  $(AtlasCxxPolicy_fflags)  $(AtlasROOT_fflags)  $(ExternalPolicy_fflags)  $(SLC5_Compat_fflags)  $(Mac105_Compat_fflags)  $(AtlasExternalArea_fflags)  $(PlatformPolicy_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(ROOT_fflags)  $(AtlasCommonPolicy_fflags)  $(AtlasDoxygen_fflags)  $(xrootd_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags)  $(AtlasCompilers_fflags)  $(LCG_Platforms_fflags)  $(CodeCheck_fflags) 
use_pp_fflags=  $(MuonMomentumCorrections_pp_fflags)  $(AtlasPolicy_pp_fflags)  $(AtlasCxxPolicy_pp_fflags)  $(AtlasROOT_pp_fflags)  $(ExternalPolicy_pp_fflags)  $(SLC5_Compat_pp_fflags)  $(Mac105_Compat_pp_fflags)  $(AtlasExternalArea_pp_fflags)  $(PlatformPolicy_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(ROOT_pp_fflags)  $(AtlasCommonPolicy_pp_fflags)  $(AtlasDoxygen_pp_fflags)  $(xrootd_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(AtlasCompilers_pp_fflags)  $(LCG_Platforms_pp_fflags)  $(CodeCheck_pp_fflags) 
use_libraries= $(AtlasPolicy_libraries)  $(AtlasCxxPolicy_libraries)  $(AtlasROOT_libraries)  $(AtlasReflex_libraries)  $(AtlasRELAX_libraries)  $(ExternalPolicy_libraries)  $(SLC5_Compat_libraries)  $(Mac105_Compat_libraries)  $(AtlasExternalArea_libraries)  $(PlatformPolicy_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(AtlasCommonPolicy_libraries)  $(AtlasDoxygen_libraries)  $(GCCXML_libraries)  $(xrootd_libraries)  $(RELAX_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries)  $(AtlasCompilers_libraries)  $(LCG_Platforms_libraries)  $(CodeCheck_libraries) 
includes= $(ppcmd)"/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/MuonSlimming/WmunuPowPyMonteCarlo/MuonMomentumCorrections" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/include" $(ppcmd)"/afs/cern.ch/user/t/tbalestr/public/17.2.10.5/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasProduction/17.8.0.2/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasOffline/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasAnalysis/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasSimulation/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasTrigger/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasReconstruction/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasEvent/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasConditions/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/AtlasCore/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/DetCommon/17.8.0/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/GAUDI/v23r6p1/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc47-opt/17.8.0/LCGCMT/LCGCMT_65/InstallArea/include" $(use_includes)
fincludes= $(includes)
MuonMomentumCorrections_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MuonMomentumCorrections_optdebug_library_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_runtime_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MuonMomentumCorrectionsGen_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MuonMomentumCorrectionsDict_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MuonMomentumCorrectionsDict_use_linkopts=  $(MuonMomentumCorrections_linkopts)  $(AtlasPolicy_linkopts)  $(AtlasCxxPolicy_linkopts)  $(AtlasROOT_linkopts)  $(ExternalPolicy_linkopts)  $(SLC5_Compat_linkopts)  $(Mac105_Compat_linkopts)  $(AtlasExternalArea_linkopts)  $(PlatformPolicy_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(ROOT_linkopts)  $(AtlasCommonPolicy_linkopts)  $(AtlasDoxygen_linkopts)  $(xrootd_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(AtlasCompilers_linkopts)  $(LCG_Platforms_linkopts)  $(CodeCheck_linkopts) 
install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MuonMomentumCorrectionsDict_optdebug_library_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MuonMomentumCorrectionsDictMerge_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MuonMomentumCorrectionsrchk_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
doxygen_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_install_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_merge_rootmap_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_merge_genconfdb_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_build_tpcnvdb_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_post_constituents_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
checkreq_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
SLC5_Compat_install_action_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
Mac105_Compat_install_action_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
check_install_runtime_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
check_install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= MuonMomentumCorrections MuonMomentumCorrections_optdebug_library install_runtime MuonMomentumCorrectionsGen MuonMomentumCorrectionsDict install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmap MuonMomentumCorrectionsDict_optdebug_library MuonMomentumCorrectionsDictMerge install_includes 
all_constituents= $(constituents)
constituentsclean= install_includesclean MuonMomentumCorrectionsDictMergeclean MuonMomentumCorrectionsDict_optdebug_libraryclean install_MuonMomentumCorrectionsDict_MuonMomentumCorrectionsdictrootmapclean MuonMomentumCorrectionsDictclean MuonMomentumCorrectionsGenclean install_runtimeclean MuonMomentumCorrections_optdebug_libraryclean MuonMomentumCorrectionsclean 
all_constituentsclean= $(constituentsclean)
rulechecker_constituents= MuonMomentumCorrectionsrchk 
rulechecker_constituentsclean= MuonMomentumCorrectionsrchkclean 
